# docker-composeのバージョン
version: "3" 

# コンテナの定義
services: 
  # nginxコンテナ
  web:
    # コンテナ名
    container_name: "web"
    build:
      dockerfile: "./web/Dockerfile"
    ports:
      - "8080:80"
    volumes:
      - "./src:/var/www/html"
  # PHPコンテナ
  php:
    container_name: "php"
    build:
      dockerfile: "./php/Dockerfile"
    volumes:
      - "./src:/var/www/html"
  # DBコンテナ
  db:
    container_name: "db"
    build:
      dockerfile: "./db/Dockerfile"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=laravel"
      - "MYSQL_PASSWORD=password"
    volumes:
      - "./db/data:/var/lib/mysql"

  # phpmyadmin
  phpmyadmin:
    build:
      dockerfile: "./phpmyadmin/Dockerfile"
    container_name: "phpmyadmin"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=laravel
      - PMA_PASSWORD=password
    links:
      - db
    ports:
      - "8888:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions
  
  # npm
  npm:
    build:
      context: "./"
      dockerfile: "./npm/Dockerfile"
    container_name: "npm"
    volumes:
      - "./src:/workspace"